Effect.exe:
    asmc64 -ws -pe -gui Blur.asm
    asmc64 -ws -pe -gui Sharpen.asm
    asmc64 -ws -pe -gui RedEyeCorrection.asm
    asmc64 -ws -pe -gui BrightnessContrast.asm
    asmc64 -ws -pe -gui HueSaturationLightness.asm
    asmc64 -ws -pe -gui Levels.asm
    asmc64 -ws -pe -gui Tint.asm
    asmc64 -ws -pe -gui ColorBalance.asm
    asmc64 -ws -pe -gui ColorMatrixEffect.asm
    asmc64 -ws -pe -gui ColorLUT.asm
    asmc64 -ws -pe -gui ColorCurve.asm
