aaindex.exe:
    asmc64 -pe -gui -D_GLPE aaindex.asm
    asmc64 -pe aargb.asm
    asmc64 -pe -gui -D_GLPE bezcurve.asm
    asmc64 -pe -gui -D_GLPE accanti.asm
    asmc64 -pe -gui -D_GLPE dof.asm
    asmc64 -pe -gui -D_GLPE aapoly.asm
    asmc64 -pe -gui -D_GLPE accpersp.asm
    asmc64 -pe -gui -D_GLPE alpha.asm
    asmc64 -pe -gui -D_GLPE alpha3D.asm
    asmc64 -pe -gui -D_GLPE bezmesh.asm
    asmc64 -pe -gui -D_GLPE bezsurf.asm
    asmc64 -pe -gui -D_GLPE clip.asm
    asmc64 -pe -gui -D_GLPE checker.asm
    asmc64 -pe -gui -D_GLPE colormat.asm
    asmc64 -pe -gui -D_GLPE cube.asm
    asmc64 -pe -gui -D_GLPE double.asm
    asmc64 -pe -gui -D_GLPE drawf.asm
    asmc64 -pe feedback.asm
    asmc64 -pe fog.asm
    asmc64 -pe -gui -D_GLPE font.asm
    asmc64 -pe -gui -D_GLPE hello.asm
    asmc64 -pe image.asm
    asmc64 -pe -gui -D_GLPE light.asm
    asmc64 -pe -gui -D_GLPE lines.asm
    asmc64 -pe -gui -D_GLPE list.asm
    asmc64 -pe -gui -D_GLPE material.asm
    asmc64 -pe -gui -D_GLPE mipmap.asm
    asmc64 -pe -gui -D_GLPE model.asm
    asmc64 -pe -gui -D_GLPE movelight.asm
    asmc64 -pe pickdepth.asm
    asmc64 -pe picksquare.asm
    asmc64 -pe -gui -D_GLPE planet.asm
    asmc64 -pe polyoff.asm
    asmc64 -pe -gui -D_GLPE polys.asm
    asmc64 -pe quadric.asm
    asmc64 -pe -gui -D_GLPE robot.asm
    asmc64 -pe -gui -D_GLPE scene.asm
    asmc64 -pe select.asm
    asmc64 -pe -gui -D_GLPE smooth.asm
    asmc64 -pe -gui -D_GLPE stencil.asm
    asmc64 -pe -gui -D_GLPE stroke.asm
    asmc64 -pe surface.asm
    asmc64 -pe -gui -D_GLPE teapots.asm
    asmc64 -pe tess.asm
    asmc64 -pe tesswind.asm
    asmc64 -pe -gui -D_GLPE texbind.asm
    asmc64 -pe -gui -D_GLPE texgen.asm
    asmc64 -pe texprox.asm
    asmc64 -pe -gui -D_GLPE texsub.asm
    asmc64 -pe -gui -D_GLPE texturesurf.asm
    asmc64 -pe -gui -D_GLPE torus.asm
    asmc64 -pe -gui -D_GLPE trim.asm
    asmc64 -pe unproject.asm
    asmc64 -pe -gui -D_GLPE varray.asm
    asmc64 -pe -gui -D_GLPE wrap.asm

