define IDD_DIALOG_FULLSCREENMAGNIFICATIONCONTROL 101
define IDC_RADIO_100                   1001
define IDC_RADIO_200                   1002
define IDC_RADIO_300                   1003
define IDC_RADIO_400                   1004
define IDC_CHECK_SETGRAYSCALE          1005
define IDC_BUTTON_GETSETTINGS          1006
define IDC_CHECK_SETINPUTTRANSFORM     1007
define IDC_CLOSE                       1008

