Effect.exe:
#    asmc64 -ws -pe -gui TestMetafile4.asm
#    asmc64 -ws -pe -gui TestMetafile6.asm
    asmc64 -ws -pe -gui ClearBrushRemapTable.asm
    asmc64 -ws -pe -gui ClearColorMatrices.asm
#    TestMetafile4
#    TestMetafile6
