ImageAttributes:
    asmc64 -ws -pe -gui ClearBrushRemapTable.asm
    asmc64 -ws -pe -gui ClearColorMatrices.asm
    asmc64 -ws -pe -gui ClearNoOp.asm
    asmc64 -ws -pe -gui GetAdjustedPalette.asm
    asmc64 -ws -pe -gui SetColorKey.asm
    asmc64 -ws -pe -gui SetOutputChannel.asm
    asmc64 -ws -pe -gui SetOutputProfile.asm
    asmc64 -ws -pe -gui SetThreshold.asm
    SetThreshold
