Graphics.exe:
    asmc64 -ws -pe -gui DrawString.asm
    asmc64 -ws -pe -gui Zooming.asm
    asmc64 -ws -pe -gui Rotating.asm
    asmc64 -ws -pe -gui Gradient.asm
    asmc64 -ws -pe -gui Sphere.asm
    asmc64 -ws -pe -gui Sphere2.asm
    asmc64 -ws -pe -gui Person.asm
    Person

