aaindex.exe:
    asmc64 -pe -gui -D_GLPE aaindex.asm
    asmc64 -pe aargb.asm
    asmc64 -pe -gui -D_GLPE bezcurve.asm
    asmc64 -pe -gui -D_GLPE accanti.asm
    asmc64 -pe -gui -D_GLPE dof.asm
    asmc64 -pe -gui -D_GLPE aapoly.asm
    asmc64 -pe -gui -D_GLPE accpersp.asm
    asmc64 -pe -gui -D_GLPE alpha.asm
    asmc64 -pe -gui -D_GLPE alpha3D.asm
    asmc64 -pe -gui -D_GLPE bezmesh.asm
    asmc64 -pe -gui -D_GLPE bezsurf.asm
    asmc64 -pe -gui -D_GLPE clip.asm
    asmc64 -pe -gui -D_GLPE checker.asm
    asmc64 -pe -gui -D_GLPE colormat.asm
    asmc64 -pe -gui -D_GLPE cube.asm
    asmc64 -pe -gui -D_GLPE double.asm
    asmc64 -pe -gui -D_GLPE drawf.asm
    asmc64 -pe feedback.asm
    asmc64 -pe fog.asm
    asmc64 -pe -gui -D_GLPE font.asm
    asmc64 -pe -gui -D_GLPE hello.asm




