ifndef GDK_PIXBUF_H
define GDK_PIXBUF_H

define GDK_PIXBUF_H_INSIDE

include glib.inc
include gdk-pixbuf/gdk-pixbuf-macros.inc
include gdk-pixbuf/gdk-pixbuf-features.inc
include glib-object.inc

include gdk-pixbuf/gdk-pixbuf-core.inc
include gdk-pixbuf/gdk-pixbuf-transform.inc
include gdk-pixbuf/gdk-pixbuf-animation.inc
include gdk-pixbuf/gdk-pixbuf-simple-anim.inc
include gdk-pixbuf/gdk-pixbuf-io.inc
include gdk-pixbuf/gdk-pixbuf-loader.inc
include gdk-pixbuf/gdk-pixbuf-enum-types.inc

include gdk-pixbuf/gdk-pixbuf-autocleanups.inc

undef GDK_PIXBUF_H_INSIDE

endif
