
avxins (ADDPD,	  vaddpd,	 P_AVX, VX_L )
avxins (ADDPS,	  vaddps,	 P_AVX, VX_L|VX_NRW )
avxins (ADDSD,	  vaddsd,	 P_AVX, 0 )
avxins (ADDSS,	  vaddss,	 P_AVX, VX_NRW )
avxins (DIVPD,	  vdivpd,	 P_AVX, VX_L )
avxins (DIVPS,	  vdivps,	 P_AVX, VX_L|VX_NRW )
avxins (DIVSD,	  vdivsd,	 P_AVX, 0 )
avxins (DIVSS,	  vdivss,	 P_AVX, VX_NRW )
avxins (MAXPD,	  vmaxpd,	 P_AVX, VX_L )
avxins (MAXPS,	  vmaxps,	 P_AVX, VX_L )
avxins (MAXSD,	  vmaxsd,	 P_AVX, 0 )
avxins (MAXSS,	  vmaxss,	 P_AVX, 0 )
avxins (MINPD,	  vminpd,	 P_AVX, VX_L )
avxins (MINPS,	  vminps,	 P_AVX, VX_L )
avxins (MINSD,	  vminsd,	 P_AVX, 0 )
avxins (MINSS,	  vminss,	 P_AVX, 0 )
avxins (MULPD,	  vmulpd,	 P_AVX, VX_L )
avxins (MULPS,	  vmulps,	 P_AVX, VX_L )
avxins (MULSD,	  vmulsd,	 P_AVX, 0 )
avxins (MULSS,	  vmulss,	 P_AVX, 0 )
avxins (SQRTPD,	  vsqrtpd,	 P_AVX, VX_L )
avxins (SQRTPS,	  vsqrtps,	 P_AVX, VX_L )
avxins (SQRTSD,	  vsqrtsd,	 P_AVX, 0 )
avxins (SQRTSS,	  vsqrtss,	 P_AVX, 0 )
avxins (SUBPD,	  vsubpd,	 P_AVX, VX_L )
avxins (SUBPS,	  vsubps,	 P_AVX, VX_L )
avxins (SUBSD,	  vsubsd,	 P_AVX, 0 )
avxins (SUBSS,	  vsubss,	 P_AVX, 0 )
avxins (CMPPD,	  vcmppd,	 P_AVX, VX_L )
avxins (CMPPS,	  vcmpps,	 P_AVX, VX_L )
avxins (CMPSD,	  vcmpsd,	 P_AVX, 0 )
avxins (CMPSS,	  vcmpss,	 P_AVX, 0 )

avxins (ANDPD,	  vandpd,	 P_AVX, VX_L )
avxins (ANDPS,	  vandps,	 P_AVX, VX_L|VX_NRW )
avxins (ANDNPD,	  vandnpd,	 P_AVX, VX_L )
avxins (ANDNPS,	  vandnps,	 P_AVX, VX_L|VX_NRW )
avxins (ORPD,	  vorpd,	 P_AVX, VX_L )
avxins (ORPS,	  vorps,	 P_AVX, VX_L )
avxins (COMISD,	  vcomisd,	 P_AVX, VX_NND )
avxins (COMISS,	  vcomiss,	 P_AVX, VX_NND|VX_NRW )
avxins (XORPD,	  vxorpd,	 P_AVX, VX_L )
avxins (XORPS,	  vxorps,	 P_AVX, VX_L )

avxins (CVTDQ2PD, vcvtdq2pd,	 P_AVX, VX_L|VX_NND|VX_HALF|VX_NRW )
avxins (CVTDQ2PS, vcvtdq2ps,	 P_AVX, VX_L|VX_NND|VX_NRW )
avxins (CVTPS2DQ, vcvtps2dq,	 P_AVX, VX_L|VX_NND|VX_NRW )
avxins (CVTTPS2DQ,vcvttps2dq,	 P_AVX, VX_L|VX_NND|VX_NRW )
avxins (CVTPS2PD, vcvtps2pd,	 P_AVX, VX_L|VX_NND|VX_HALF|VX_NRW )
avxins (CVTSD2SI, vcvtsd2si,	 P_AVX, VX_NND|VX_NRW )
avxins (CVTTSD2SI,vcvttsd2si,	 P_AVX, VX_NND|VX_NRW )
avxins (CVTSD2SS, vcvtsd2ss,	 P_AVX, 0 )
avxins (CVTSI2SD, vcvtsi2sd,	 P_AVX, VX_NRW )
avxins (CVTSI2SS, vcvtsi2ss,	 P_AVX, VX_NRW )
avxins (CVTSS2SD, vcvtss2sd,	 P_AVX, VX_NRW )
avxins (CVTSS2SI, vcvtss2si,	 P_AVX, VX_NND|VX_NRW )
avxins (CVTTSS2SI,vcvttss2si,	 P_AVX, VX_NND|VX_NRW )

avxins (ADDSUBPD, vaddsubpd,	 P_AVX, VX_L )
avxins (ADDSUBPS, vaddsubps,	 P_AVX, VX_L )
avxins (BLENDPD , vblendpd ,	 P_AVX, VX_L )
avxins (BLENDPS , vblendps ,	 P_AVX, VX_L )
avxins (DPPD	, vdppd	   ,	 P_AVX, 0 )
avxins (DPPS	, vdpps	   ,	 P_AVX, VX_L )
avxins (EXTRACTPS,vextractps,	 P_AVX, VX_NND|VX_NRW )
avxins (HADDPD	, vhaddpd  ,	 P_AVX, VX_L )
avxins (HADDPS	, vhaddps  ,	 P_AVX, VX_L )
avxins (HSUBPD	, vhsubpd  ,	 P_AVX, VX_L )
avxins (HSUBPS	, vhsubps  ,	 P_AVX, VX_L )
avxins (INSERTPS, vinsertps,	 P_AVX, VX_NRW )
avxins (LDDQU	, vlddqu   ,	 P_AVX, VX_L|VX_NND )
avxins (LDMXCSR , vldmxcsr ,	 P_AVX, 0 )
avxins (STMXCSR , vstmxcsr ,	 P_AVX, 0 )

avxins (MASKMOVDQU,vmaskmovdqu,	 P_AVX, VX_NND )
avxins (MOVAPD	, vmovapd  ,	 P_AVX, VX_L|VX_NND )
avxins (MOVAPS	, vmovaps  ,	 P_AVX, VX_L|VX_NND|VX_NRW )
avxins (MOVD	, vmovd	   ,	 P_AVX, VX_NND|VX_NRW )
avxins (MOVQ	, vmovq	   ,	 P_AVX, VX_NND )
avxins (MOVDQA	, vmovdqa  ,	 P_AVX, VX_L|VX_NND )
avxins (MOVDQU	, vmovdqu  ,	 P_AVX, VX_L|VX_NND )
avxins (MOVHLPS , vmovhlps ,	 P_AVX, VX_NRW )
avxins (MOVLHPS , vmovlhps ,	 P_AVX, VX_NRW )
avxins (MOVHPD	, vmovhpd  ,	 P_AVX, VX_NMEM )
avxins (MOVHPS	, vmovhps  ,	 P_AVX, VX_NMEM|VX_NRW )
avxins (MOVLPD	, vmovlpd  ,	 P_AVX, VX_NMEM )
avxins (MOVLPS	, vmovlps  ,	 P_AVX, VX_NMEM|VX_NRW )
avxins (MOVSD	, vmovsd   ,	 P_AVX, VX_NMEM )
avxins (MOVSS	, vmovss   ,	 P_AVX, VX_NMEM|VX_NRW )
avxins (MOVNTDQ , vmovntdq ,	 P_AVX, VX_L|VX_NND|VX_NRW )
avxins (MOVNTDQA, vmovntdqa,	 P_AVX, VX_NND|VX_NRW )
avxins (MOVNTPD , vmovntpd ,	 P_AVX, VX_L|VX_NND )
avxins (MOVNTPS , vmovntps ,	 P_AVX, VX_L|VX_NND|VX_NRW )
avxins (MOVSHDUP, vmovshdup,	 P_AVX, VX_L|VX_NND )
avxins (MOVSLDUP, vmovsldup,	 P_AVX, VX_L|VX_NND )
avxins (MOVUPD	, vmovupd  ,	 P_AVX, VX_L|VX_NND )
avxins (MOVUPS	, vmovups  ,	 P_AVX, VX_L|VX_NND|VX_NRW )

avxins (MPSADBW , vmpsadbw ,	 P_AVX, 0 )

avxins (PABSB	, vpabsb   ,	 P_AVX, VX_NND|VX_NRW )
avxins (PABSW	, vpabsw   ,	 P_AVX, VX_NND|VX_NRW )
avxins (PABSD	, vpabsd   ,	 P_AVX, VX_NND|VX_NRW )
avxins (PACKSSWB, vpacksswb,	 P_AVX, 0 )
avxins (PACKSSDW, vpackssdw,	 P_AVX, 0 )
avxins (PACKUSWB, vpackuswb,	 P_AVX, 0 )
avxins (PACKUSDW, vpackusdw,	 P_AVX, 0 )
avxins (PADDB	, vpaddb   ,	 P_AVX, VX_NRW )
avxins (PADDW	, vpaddw   ,	 P_AVX, VX_NRW )
avxins (PADDD	, vpaddd   ,	 P_AVX, VX_NRW )
avxins (PADDQ	, vpaddq   ,	 P_AVX, 0 )
avxins (PADDSB	, vpaddsb  ,	 P_AVX, VX_NRW )
avxins (PADDSW	, vpaddsw  ,	 P_AVX, VX_NRW )
avxins (PADDUSB , vpaddusb ,	 P_AVX, VX_NRW )
avxins (PADDUSW , vpaddusw ,	 P_AVX, VX_NRW )
avxins (PALIGNR , vpalignr ,	 P_AVX, 0 )
avxins (PAND	, vpand	   ,	 P_AVX, 0 )
avxins (PANDN	, vpandn   ,	 P_AVX, 0 )
avxins (PAVGB	, vpavgb   ,	 P_AVX, VX_NRW )
avxins (PAVGW	, vpavgw   ,	 P_AVX, VX_NRW )
avxins (PBLENDW , vpblendw ,	 P_AVX, 0 )
avxins (PCMPESTRI,vpcmpestri,	 P_AVX, VX_NND )
avxins (PCMPESTRM,vpcmpestrm,	 P_AVX, VX_NND )
avxins (PCMPISTRI,vpcmpistri,	 P_AVX, VX_NND )
avxins (PCMPISTRM,vpcmpistrm,	 P_AVX, VX_NND )
avxins (PCMPEQB	 ,vpcmpeqb  ,	 P_AVX, 0 )
avxins (PCMPEQW	 ,vpcmpeqw  ,	 P_AVX, 0 )
avxins (PCMPEQD	 ,vpcmpeqd  ,	 P_AVX, 0 )
avxins (PCMPEQQ	 ,vpcmpeqq  ,	 P_AVX, 0 )
avxins (PCMPGTB	 ,vpcmpgtB  ,	 P_AVX, 0 )
avxins (PCMPGTW	 ,vpcmpgtw  ,	 P_AVX, 0 )
avxins (PCMPGTD	 ,vpcmpgtd  ,	 P_AVX, 0 )
avxins (PCMPGTQ	 ,vpcmpgtq  ,	 P_AVX, 0 )
avxins (PEXTRB	 ,vpextrb   ,	 P_AVX, VX_L|VX_NND|VX_NRW )
avxins (PEXTRW	 ,vpextrw   ,	 P_AVX, VX_L|VX_NND|VX_NRW )
avxins (PEXTRD	 ,vpextrd   ,	 P_AVX, VX_L|VX_NND|VX_NRW )
avxins (PINSRB	 ,vpinsrb   ,	 P_AVX, VX_L|VX_NRW )
avxins (PINSRW	 ,vpinsrw   ,	 P_AVX, VX_L|VX_NRW )
avxins (PINSRD	 ,vpinsrd   ,	 P_AVX, VX_L|VX_NRW )

avxins (PEXTRQ	 ,vpextrq   ,	 P_AVX, VX_NND )
avxins (PINSRQ	 ,vpinsrq   ,	 P_AVX, 0 )

avxins (PHADDW	 ,vphaddw   ,	 P_AVX, 0 )
avxins (PHADDD	 ,vphaddd   ,	 P_AVX, 0 )
avxins (PHADDSW	 ,vphaddsw  ,	 P_AVX, 0 )
avxins (PHMINPOSUW,vphminposuw,	 P_AVX, VX_NND )
avxins (PHSUBW	 ,vphsubw   ,	 P_AVX, 0 )
avxins (PHSUBD	 ,vphsubd   ,	 P_AVX, 0 )
avxins (PHSUBSW	 ,vphsubsw  ,	 P_AVX, 0 )
avxins (PMADDWD	 ,vpmaddwd  ,	 P_AVX, 0 )
avxins (PMADDUBSW,vpmaddubsw,	 P_AVX, 0 )
avxins (PMAXSB	 ,vpmaxsb   ,	 P_AVX, 0 )
avxins (PMAXSW	 ,vpmaxsw   ,	 P_AVX, 0 )
avxins (PMAXSD	 ,vpmaxsd   ,	 P_AVX, 0 )
avxins (PMAXUB	 ,vpmaxub   ,	 P_AVX, 0 )
avxins (PMAXUW	 ,vpmaxuw   ,	 P_AVX, 0 )
avxins (PMAXUD	 ,vpmaxud   ,	 P_AVX, 0 )
avxins (PMINSB	 ,vpminsb   ,	 P_AVX, 0 )
avxins (PMINSW	 ,vpminsw   ,	 P_AVX, 0 )
avxins (PMINSD	 ,vpminsd   ,	 P_AVX, 0 )
avxins (PMINUB	 ,vpminub   ,	 P_AVX, 0 )
avxins (PMINUW	 ,vpminuw   ,	 P_AVX, 0 )
avxins (PMINUD	 ,vpminud   ,	 P_AVX, 0 )
avxins (PMOVMSKB ,vpmovmskb ,	 P_AVX, VX_NND )
avxins (PMOVSXBW ,vpmovsxbw ,	 P_AVX, VX_NND|VX_NRW )
avxins (PMOVSXBD ,vpmovsxbd ,	 P_AVX, VX_NND|VX_NRW )
avxins (PMOVSXBQ ,vpmovsxbq ,	 P_AVX, VX_NND|VX_NRW )
avxins (PMOVSXWD ,vpmovsxwd ,	 P_AVX, VX_NND|VX_NRW )
avxins (PMOVSXWQ ,vpmovsxwq ,	 P_AVX, VX_NND|VX_NRW )
avxins (PMOVSXDQ ,vpmovsxdq ,	 P_AVX, VX_NND|VX_NRW )
avxins (PMOVZXBW ,vpmovzxbw ,	 P_AVX, VX_NND|VX_NRW )
avxins (PMOVZXBD ,vpmovzxbd ,	 P_AVX, VX_NND|VX_NRW )
avxins (PMOVZXBQ ,vpmovzxbq ,	 P_AVX, VX_NND|VX_NRW )
avxins (PMOVZXWD ,vpmovzxwd ,	 P_AVX, VX_NND|VX_NRW )
avxins (PMOVZXWQ ,vpmovzxwq ,	 P_AVX, VX_NND|VX_NRW )
avxins (PMOVZXDQ ,vpmovzxdq ,	 P_AVX, VX_NND|VX_NRW )
avxins (PMULHUW	 ,vpmulhuw  ,	 P_AVX, 0 )
avxins (PMULHRSW ,vpmulhrsw ,	 P_AVX, 0 )
avxins (PMULHW	 ,vpmulhw   ,	 P_AVX, 0 )
avxins (PMULLW	 ,vpmullw   ,	 P_AVX, 0 )
avxins (PMULLD	 ,vpmulld   ,	 P_AVX, VX_NRW )
avxins (PMULUDQ	 ,vpmuludq  ,	 P_AVX, 0 )
avxins (PMULDQ	 ,vpmuldq   ,	 P_AVX, 0 )
avxins (POR	 ,vpor	    ,	 P_AVX, 0 )
avxins (PSADBW	 ,vpsadbw   ,	 P_AVX, 0 )
avxins (PSHUFB	 ,vpshufb   ,	 P_AVX, 0 )
avxins (PSHUFD	 ,vpshufd   ,	 P_AVX, VX_NND )
avxins (PSHUFHW	 ,vpshufhw  ,	 P_AVX, VX_NND )
avxins (PSHUFLW	 ,vpshuflw  ,	 P_AVX, VX_NND )
avxins (PSIGNB	 ,vpsignb   ,	 P_AVX, 0 )
avxins (PSIGNW	 ,vpsignw   ,	 P_AVX, 0 )
avxins (PSIGND	 ,vpsignd   ,	 P_AVX, 0 )
avxins (PSLLDQ	 ,vpslldq   ,	 P_AVX, VX_HALF|VX_L|VX_DST|VX_NRW )
avxins (PSRLDQ	 ,vpsrldq   ,	 P_AVX, VX_HALF|VX_L|VX_DST|VX_NRW )
avxins (PSLLW	 ,vpsllw    ,	 P_AVX, VX_HALF|VX_DST|VX_NRW )
avxins (PSLLD	 ,vpslld    ,	 P_AVX, VX_HALF|VX_DST|VX_NRW )
avxins (PSLLQ	 ,vpsllq    ,	 P_AVX, VX_HALF|VX_DST )
avxins (PSRAW	 ,vpsraw    ,	 P_AVX, VX_HALF|VX_DST|VX_NRW )
avxins (PSRAD	 ,vpsrad    ,	 P_AVX, VX_HALF|VX_DST|VX_NRW )
avxins (PSRLW	 ,vpsrlw    ,	 P_AVX, VX_HALF|VX_DST|VX_NRW )
avxins (PSRLD	 ,vpsrld    ,	 P_AVX, VX_HALF|VX_DST|VX_NRW )
avxins (PSRLQ	 ,vpsrlq    ,	 P_AVX, VX_HALF|VX_DST )
avxins (PTEST	 ,vptest    ,	 P_AVX, VX_L|VX_NND )
avxins (PSUBB	 ,vpsubb    ,	 P_AVX, 0 )
avxins (PSUBW	 ,vpsubw    ,	 P_AVX, 0 )
avxins (PSUBD	 ,vpsubd    ,	 P_AVX, 0 )
avxins (PSUBQ	 ,vpsubq    ,	 P_AVX, 0 )
avxins (PSUBSB	 ,vpsubsb   ,	 P_AVX, 0 )
avxins (PSUBSW	 ,vpsubsw   ,	 P_AVX, 0 )
avxins (PSUBUSB	 ,vpsubusb  ,	 P_AVX, 0 )
avxins (PSUBUSW	 ,vpsubusw  ,	 P_AVX, 0 )
avxins (PUNPCKHBW ,vpunpckhbw,	 P_AVX, 0 )
avxins (PUNPCKHWD ,vpunpckhwd,	 P_AVX, 0 )
avxins (PUNPCKHDQ ,vpunpckhdq,	 P_AVX, 0 )
avxins (PUNPCKHQDQ,vpunpckhqdq,	 P_AVX, 0 )
avxins (PUNPCKLBW ,vpunpcklbw,	 P_AVX, 0 )
avxins (PUNPCKLWD ,vpunpcklwd,	 P_AVX, 0 )
avxins (PUNPCKLDQ ,vpunpckldq,	 P_AVX, 0 )
avxins (PUNPCKLQDQ,vpunpcklqdq,	 P_AVX, 0 )
avxins (PXOR	 ,vpxor	    ,	 P_AVX, 0 )

avxins (RCPPS	 ,vrcpps    ,	 P_AVX, VX_L|VX_NND )
avxins (RCPSS	 ,vrcpss    ,	 P_AVX, 0 )
avxins (RSQRTPS	 ,vrsqrtps  ,	 P_AVX, VX_L|VX_NND )
avxins (RSQRTSS	 ,vrsqrtss  ,	 P_AVX, 0 )
avxins (ROUNDPD	 ,vroundpd  ,	 P_AVX, VX_L|VX_NND )
avxins (ROUNDPS	 ,vroundps  ,	 P_AVX, VX_L|VX_NND )
avxins (ROUNDSD	 ,vroundsd  ,	 P_AVX, 0 )
avxins (ROUNDSS	 ,vroundss  ,	 P_AVX, 0 )
avxins (SHUFPD	 ,vshufpd   ,	 P_AVX, VX_L )
avxins (SHUFPS	 ,vshufps   ,	 P_AVX, VX_L )
avxins (UCOMISD	 ,vucomisd  ,	 P_AVX, VX_NND )
avxins (UCOMISS	 ,vucomiss  ,	 P_AVX, VX_NND|VX_NRW )
avxins (UNPCKHPD ,vunpckhpd ,	 P_AVX, VX_L )
avxins (UNPCKHPS ,vunpckhps ,	 P_AVX, VX_L )
avxins (UNPCKLPD ,vunpcklpd ,	 P_AVX, VX_L )
avxins (UNPCKLPS ,vunpcklps ,	 P_AVX, VX_L )
