
res( T_DOT_NAME,       4, 5, name,      .name      )
res( T_DOT_PAGE,       4, 5, page,      .page      )
res( T_DOT_SUBTITLE,   8, 9, subtitle,  .subtitle  )
res( T_DOT_SUBTTL,     6, 7, subttl,    .subttl    )
res( T_DOT_TITLE,      5, 6, title,     .title     )
res( T_DOT_LOW,        3, 4, low,       .low       )
res( T_DOT_HIGH,       4, 5, high,      .high      )
res( T_DOT_SIZE,       4, 5, size,      .size      )
res( T_DOT_LENGTH,     6, 7, length,    .length    )
res( T_DOT_THIS,       4, 5, this,      .this      )
res( T_DOT_MASK,       4, 5, mask,      .mask      )
res( T_DOT_WIDTH,      5, 6, width,     .width     )
res( T_TYPEOF,         4, 6, type,      typeof     )
