ifndef __GDK_WIN32_H__
define __GDK_WIN32_H__

define __GDKWIN32_H_INSIDE__

include gdk/win32/gdkwin32cursor.inc
include gdk/win32/gdkwin32display.inc
include gdk/win32/gdkwin32displaymanager.inc
include gdk/win32/gdkwin32dnd.inc
include gdk/win32/gdkwin32screen.inc
include gdk/win32/gdkwin32surface.inc
include gdk/win32/gdkwin32misc.inc
include gdk/win32/gdkwin32monitor.inc
include gdk/win32/gdkwin32glcontext.inc

undef __GDKWIN32_H_INSIDE__

endif
