test.exe:
    asmc64 -pe -ws getguid.asm
    asmc64 -pe -ws openiid.asm
    asmc64 -pe -ws iidname.asm
    getguid makefile
    #openiid {7732ABAA-5B88-11E9-A107-A434D96DDF3E}
    #iidname {7732ABAA-5B88-11E9-A107-A434D96DDF3E}
    pause

