ifndef __ADSIID_H__
define __ADSIID_H__
.pragma list(push, 0)

externdef LIBID_ADs:GUID
externdef IID_IADs:GUID
externdef IID_IADsContainer:GUID
externdef IID_IADsNamespaces:GUID

externdef IID_IADsDomain:GUID
externdef IID_IADsUser:GUID
externdef IID_IADsComputerOperations:GUID
externdef IID_IADsComputer:GUID

externdef IID_IADsGroup:GUID
externdef IID_IADsMembers:GUID

externdef IID_IADsPrintQueue:GUID
externdef IID_IADsPrintQueueOperations:GUID

externdef IID_IADsPrintJobOperations:GUID
externdef IID_IADsPrintJob:GUID
externdef IID_IADsCollection:GUID

externdef IID_IADsServiceOperations:GUID
externdef IID_IADsService:GUID

externdef IID_IADsFileServiceOperations:GUID
externdef IID_IADsFileService:GUID

externdef IID_IADsResource:GUID
externdef IID_IADsSession:GUID
externdef IID_IADsFileShare:GUID
externdef IID_IADsSchema:GUID
externdef IID_IADsClass:GUID
externdef IID_IADsProperty:GUID
externdef IID_IADsSyntax:GUID

externdef IID_IADsLocality:GUID
externdef IID_IADsO:GUID
externdef IID_IADsOU:GUID
externdef IID_IADsOpenDSObject:GUID
externdef IID_IADsSearch:GUID
externdef IID_IADsPropertyList:GUID

externdef IID_IDSObject:GUID
externdef IID_IDSSearch:GUID
externdef IID_IDSAttrMgmt:GUID

externdef IID_IDirectorySearch:GUID
externdef IID_IDirectoryObject:GUID
externdef IID_IDirectoryAttrMgmt:GUID

externdef CLSID_LDAPConnectionObject:GUID
externdef CLSID_LDAPObject:GUID
externdef CLSID_UmiLDAPQueryObject:GUID
externdef CLSID_WinNTConnectionObject:GUID
externdef CLSID_WinNTObject:GUID

externdef CLSID_ADsDSOObject:GUID
externdef DBGUID_LDAPDialect:GUID
externdef DBPROPSET_ADSISEARCH:GUID
externdef DBPROPSET_ADSIBIND:GUID

.pragma list(pop)
endif

