.pragma list(push, 0)

NAMESPACE_CLASS_NAME    equ <"Namespace">
COUNTRY_CLASS_NAME      equ <"Country">
LOCALITY_CLASS_NAME     equ <"Locality"> >
ORGANIZATION_CLASS_NAME equ <"Organization">          >
ORGANIZATIONUNIT_CLASS_NAME equ <"Organizational Unit">
DOMAIN_CLASS_NAME       equ <"Domain">
COMPUTER_CLASS_NAME     equ <"Computer">
USER_CLASS_NAME         equ <"User">
GROUP_CLASS_NAME        equ <"Group">
GLOBALGROUP_CLASS_NAME  equ <"GlobalGroup">
LOCALGROUP_CLASS_NAME   equ <"LocalGroup">
SERVICE_CLASS_NAME      equ <"Service">
FILESERVICE_CLASS_NAME  equ <"FileService">
SESSION_CLASS_NAME      equ <"Session">
RESOURCE_CLASS_NAME     equ <"Resource">
FILESHARE_CLASS_NAME    equ <"FileShare">
PRINTER_CLASS_NAME      equ <"PrintQueue">
PRINTJOB_CLASS_NAME     equ <"PrintJob">
SCHEMA_CLASS_NAME       equ <"Schema">
CLASS_CLASS_NAME        equ <"Class">
PROPERTY_CLASS_NAME     equ <"Property">
SYNTAX_CLASS_NAME       equ <"Syntax">
ROOTDSE_CLASS_NAME      equ <"RootDSE">

NO_SCHEMA               equ <"">
DOMAIN_SCHEMA_NAME      equ <"Domain">
COMPUTER_SCHEMA_NAME    equ <"Computer">
USER_SCHEMA_NAME        equ <"User">
GROUP_SCHEMA_NAME       equ <"Group">
GLOBALGROUP_SCHEMA_NAME equ <"GlobalGroup">
LOCALGROUP_SCHEMA_NAME  equ <"LocalGroup">
SERVICE_SCHEMA_NAME     equ <"Service">
PRINTER_SCHEMA_NAME     equ <"PrintQueue">
PRINTJOB_SCHEMA_NAME    equ <"PrintJob">
FILESERVICE_SCHEMA_NAME equ <"FileService">
SESSION_SCHEMA_NAME     equ <"Session">
RESOURCE_SCHEMA_NAME    equ <"Resource">
FILESHARE_SCHEMA_NAME   equ <"FileShare">
FPNW_FILESERVICE_SCHEMA_NAME equ <"FPNWFileService">
FPNW_SESSION_SCHEMA_NAME equ <"FPNWSession">
FPNW_RESOURCE_SCHEMA_NAME equ <"FPNWResource">
FPNW_FILESHARE_SCHEMA_NAME equ <"FPNWFileShare">

.pragma list(pop)
