ifndef _GDIPLUSGPSTUBS_H
define _GDIPLUSGPSTUBS_H

GpStatus            typedef Status
GpFillMode          typedef FillMode
GpWrapMode          typedef WrapMode
GpUnit              typedef Unit
GpCoordinateSpace   typedef CoordinateSpace
GpPointF            typedef PointF
GpPoint             typedef Point
GpRectF             typedef RectF
GpRect              typedef Rect
GpSizeF             typedef SizeF
GpHatchStyle        typedef HatchStyle
GpDashStyle         typedef DashStyle
GpLineCap           typedef LineCap
GpDashCap           typedef DashCap


GpPenAlignment      typedef PenAlignment

GpLineJoin          typedef LineJoin
GpPenType           typedef PenType

;GpMatrix            typedef Matrix
GpBrushType         typedef BrushType
GpMatrixOrder       typedef MatrixOrder
GpFlushIntention    typedef FlushIntention
GpPathData          typedef PathData

endif  ;; NOT _GDIPLUSGPSTUBS.HPP


