CreateDevice.exe:
    asmc64 -ws -pe -gui CreateDevice.asm
    asmc64 -ws -pe -gui Vertices.asm
    asmc64 -ws -pe -gui Matrices.asm
    asmc64 -ws -pe -gui Lights.asm
    asmc64 -ws -pe -gui Textures.asm
    asmc64 -ws -pe -gui Meshes.asm
